# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: NN0Y hamshack online
email: harris@nn0y.com
description: >- # this means to ignore newlines until "baseurl:"
  Harris NN0Y's page dedicated to ham radio projects.
github_username: parsimo2010
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Denver # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: solarized-dark

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Harris Butler"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I am Amateur Extra operator, callsign NN0Y."
  links:
    - label: "QRZ"
      icon: "fas fa-fw fa-external-link-square"
      url: "https://www.qrz.com/db/nn0y"
    - label: "eQSL"
      icon: "fab fa-fw fa-external-link-square"
      url: "https://www.eqsl.cc/Member.cfm?NN0Y"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/parsimo2010"

footer:
  links:
    - label: "QRZ"
      icon: "fas fa-fw fa-external-link-square"
      url: "https://www.qrz.com/db/nn0y"
    - label: "eQSL"
      icon: "fab fa-fw fa-external-link-square"
      url: "https://www.eqsl.cc/Member.cfm?NN0Y"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/parsimo2010"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
